apiVersion: apps/v1
kind: Deployment
metadata:
 name: php-apache
 namespace: autoscale-php-apache
spec:
 selector:
   matchLabels:
     app: php-apache
 replicas: 1
 template:
   metadata:
     labels:
       app: php-apache
   spec:
     containers:
     - name: php-apache
       image: k8s.gcr.io/hpa-example
       ports:
       - containerPort: 80
       resources:
         limits:
           cpu: 500m
           memory: 512Mi
         requests:
           cpu: 250m
           memory: 256Mi
