apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql-app
type: Opaque
data:
  mysql-user: eW92YW4tZXNjb2Jhcg==
  mysql-password: c2VjcmV0cGFzc3dvcmQ=
  mysql-root-password: c3VwZXJyb290cHdk
